***
10 random seeds: range(20, 30)
for data creation for each type of spammer

invoke pgem for 10 random seeds: range(10)

get pgem accuracy (+- std dev), wacc and tau

save in results/spammer_type/pgem.csv
***

## Device Setup

In [1]:
!nvidia-smi

Sun Dec 21 17:10:20 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:17:00.0 Off |                    0 |
| N/A   47C    P0              44W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:31:00.0 Off |                    0 |
| N/A   71C    P0             303W / 300W |  49603MiB / 81920MiB |     98%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          Off | 00000000:4B:00.0 Off |                    0 |
| N/A   72C    P0             293W / 300W |  49603MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          Off | 00000000:CA:00.0 Off |                    0 |
| N/A   34C    P0              59W / 300W |   3129MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

In [2]:
import os
import torch
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda

In [3]:
print(f"Current PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")

Current PyTorch version: 2.9.1+cu128
CUDA available: True
CUDA version: 12.8

### Importing PGEM

In [4]:
import sys
sys.path.insert(0, "../")
sys.path.insert(1, "../../")

from spammer_types import *
from util import *
import opt_fair
from distribution_utils import crowd_bt_dist, logistic_preference_dist, comparisons_to_df, safe_kendalltau, to_numpy
from metrics import compute_acc, compute_weighted_acc
from pgem import EMWrapper

## Passage dataset

### Get the original df of passage dataset

In [5]:
df_path = "../../real_data/faceage/data/crowd_labels.csv"

In [6]:
import pandas as pd
df = pd.read_csv(df_path)
def sort_df(df, column_name):
        # Sort by a specific column (replace 'column_name' with your column)
        df_sorted = df.sort_values(by=column_name, ascending=True)  # or ascending=False

        return df_sorted
df = sort_df(df, 'performer')
df[['left', 'right', 'label', 'performer']].head()

,left,right,label,performer
0,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,0
6306,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,0
6176,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,0
6175,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,0
6174,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,https://tlk.s3.yandex.net/annotation_tasks/IMD...,0

In [7]:
percents = [10, 20, 40, 60, 80]
# percents = [10]

In [8]:
import pickle

with open("../../real_data/faceage/data/FaceAgeDF.pickle", "rb") as handle:
    df_passage = pickle.load(handle)
df_passage

                                      full_path  score  gender
0     nm1442940_rm3965098752_1996-10-3_2006.jpg     10     0.0
1     nm4832920_rm1781768448_2003-8-28_2013.jpg     10     0.0
2      nm0652089_rm860657920_1992-3-10_2002.jpg     10     0.0
3     nm0004917_rm1493730304_1969-5-12_1979.jpg     10     0.0
4     nm1113550_rm1332711936_1996-4-14_2006.jpg     10     0.0
...                                         ...    ...     ...
9145                 475367_1941-08-03_2011.jpg     70     1.0
9146                 304085_1919-07-07_1989.jpg     70     1.0
9147  nm0001627_rm4164078592_1927-2-20_1997.jpg     70     1.0
9148  nm0000024_rm1715129344_1904-4-14_1974.jpg     70     1.0
9149  nm0000323_rm3114703104_1933-3-14_2003.jpg     70     1.0

[9150 rows x 3 columns]

In [9]:
size = len(df_passage)
print(size)
classes = [0] * size
# for faceage it would be classes = df_passage['gender']

9150

In [10]:
gt_df = df_passage

### Addition of Random Guessors

In [11]:
spammer_type = "random"

In [12]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [13]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [14]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_random_spammer(df, percent, seed=sd)
        PC_faceage = df_to_pickle_faceage(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

Unique performers: 4500
4500
cuda
cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:17,  5.51it/s]

Iter 000: Log-likelihood = -0.387098

 24%|████████████████████████████▎                                                                                         | 24/100 [00:04<00:13,  5.64it/s]

Converged at iter 24, Log-likelihood change = 8.642673e-07
cuda
cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:09, 10.37it/s]

Iter 000: Log-likelihood = -0.387012

 32%|█████████████████████████████████████▊                                                                                | 32/100 [00:05<00:10,  6.27it/s]

Converged at iter 32, Log-likelihood change = 2.384186e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:29,  3.34it/s]

Iter 000: Log-likelihood = -0.387613

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:10<00:21,  3.19it/s]

Converged at iter 33, Log-likelihood change = 8.046627e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:11,  8.99it/s]

Iter 000: Log-likelihood = -0.387400

 47%|███████████████████████████████████████████████████████▍                                                              | 47/100 [00:09<00:10,  4.98it/s]

Converged at iter 47, Log-likelihood change = 6.258488e-07
cuda
cuda

  0%|                                                                                                                               | 0/100 [00:00<?, ?it/s]

Iter 000: Log-likelihood = -0.386969

 26%|██████████████████████████████▋                                                                                       | 26/100 [00:05<00:15,  4.77it/s]

Converged at iter 26, Log-likelihood change = 1.490116e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:11,  8.91it/s]

Iter 000: Log-likelihood = -0.387211

 32%|█████████████████████████████████████▊                                                                                | 32/100 [00:06<00:13,  5.03it/s]

Converged at iter 32, Log-likelihood change = 4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:14,  7.03it/s]

Iter 000: Log-likelihood = -0.387156

 77%|██████████████████████████████████████████████████████████████████████████████████████████▊                           | 77/100 [00:14<00:04,  5.48it/s]

Converged at iter 77, Log-likelihood change = 9.238720e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:10,  9.31it/s]

Iter 000: Log-likelihood = -0.387170

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:05<00:13,  5.09it/s]

Converged at iter 30, Log-likelihood change = 6.854534e-07
cuda

cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:08, 11.13it/s]

Iter 000: Log-likelihood = -0.387251

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:03<00:08,  7.95it/s]

Converged at iter 29, Log-likelihood change = 5.662441e-07
cuda
cuda

  0%|                                                                                                                               | 0/100 [00:00<?, ?it/s]

Iter 000: Log-likelihood = -0.387137

 26%|██████████████████████████████▋                                                                                       | 26/100 [00:04<00:13,  5.61it/s]

Converged at iter 26, Log-likelihood change = -7.450581e-07
Unique performers: 4500
4500
cuda
cuda

  0%|                                                                                                                               | 0/100 [00:00<?, ?it/s]

Iter 000: Log-likelihood = -0.387092

 35%|█████████████████████████████████████████▎                                                                            | 35/100 [00:06<00:12,  5.10it/s]

Converged at iter 35, Log-likelihood change = 7.450581e-07
cuda

cuda

  0%|                                                                                                                               | 0/100 [00:00<?, ?it/s]

Iter 000: Log-likelihood = -0.386983

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:04<00:11,  6.11it/s]

Converged at iter 27, Log-likelihood change = 8.940697e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:28,  3.43it/s]

Iter 000: Log-likelihood = -0.387592

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:12<00:00,  8.24it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:14,  6.96it/s]

Iter 000: Log-likelihood = -0.387371

 55%|████████████████████████████████████████████████████████████████▉                                                     | 55/100 [00:13<00:11,  3.96it/s]

Converged at iter 55, Log-likelihood change = 5.364418e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:16,  5.85it/s]

Iter 000: Log-likelihood = -0.387052

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:20<00:00,  4.98it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:11,  8.71it/s]

Iter 000: Log-likelihood = -0.387183

 26%|██████████████████████████████▋                                                                                       | 26/100 [00:18<00:51,  1.43it/s]

Converged at iter 26, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:53,  1.86it/s]

Iter 000: Log-likelihood = -0.387186

 34%|████████████████████████████████████████                                                                              | 34/100 [00:29<00:57,  1.15it/s]

Converged at iter 34, Log-likelihood change = 7.748604e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:48,  2.02it/s]

Iter 000: Log-likelihood = -0.387143

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:15<00:35,  1.99it/s]

Converged at iter 30, Log-likelihood change = 9.238720e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:23,  4.25it/s]

Iter 000: Log-likelihood = -0.387205

 28%|█████████████████████████████████                                                                                     | 28/100 [00:12<00:32,  2.21it/s]

Converged at iter 28, Log-likelihood change = 8.642673e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:16,  1.29it/s]

Iter 000: Log-likelihood = -0.387324

 38%|████████████████████████████████████████████▊                                                                         | 38/100 [00:08<00:14,  4.25it/s]

Converged at iter 38, Log-likelihood change = 7.748604e-07
Unique performers: 4500
4500
cuda
cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:21,  4.48it/s]

Iter 000: Log-likelihood = -0.387053

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:15<00:31,  2.12it/s]

Converged at iter 33, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:01,  1.61it/s]

Iter 000: Log-likelihood = -0.387049

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:25<00:57,  1.20it/s]

Converged at iter 31, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:01<01:44,  1.06s/it]

Iter 000: Log-likelihood = -0.387582

 53%|██████████████████████████████████████████████████████████████▌                                                       | 53/100 [00:43<00:38,  1.23it/s]

Converged at iter 53, Log-likelihood change = 8.344650e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.41it/s]

Iter 000: Log-likelihood = -0.387468

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:22<00:00,  1.22it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:34,  2.88it/s]

Iter 000: Log-likelihood = -0.386941

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:31<01:09,  1.01s/it]

Converged at iter 31, Log-likelihood change = 8.046627e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:42,  2.34it/s]

Iter 000: Log-likelihood = -0.387171

 35%|█████████████████████████████████████████▎                                                                            | 35/100 [00:23<00:43,  1.49it/s]

Converged at iter 35, Log-likelihood change = -7.152557e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:55,  1.79it/s]

Iter 000: Log-likelihood = -0.387082

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:23<00:00,  1.19it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.40it/s]

Iter 000: Log-likelihood = -0.387280

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:04<00:00,  1.54it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:29,  3.41it/s]

Iter 000: Log-likelihood = -0.387244

 44%|███████████████████████████████████████████████████▉                                                                  | 44/100 [00:11<00:14,  3.90it/s]

Converged at iter 44, Log-likelihood change = 9.536743e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:20,  4.77it/s]

Iter 000: Log-likelihood = -0.387321

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:05<00:11,  5.89it/s]

Converged at iter 31, Log-likelihood change = 8.344650e-07
Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:37,  2.66it/s]

Iter 000: Log-likelihood = -0.387142

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:17<00:47,  1.53it/s]

Converged at iter 27, Log-likelihood change = -7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:25,  3.83it/s]

Iter 000: Log-likelihood = -0.387010

 56%|██████████████████████████████████████████████████████████████████                                                    | 56/100 [00:49<00:38,  1.13it/s]

Converged at iter 56, Log-likelihood change = 7.748604e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:01<01:54,  1.15s/it]

Iter 000: Log-likelihood = -0.387604

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:43<01:36,  1.40s/it]

Converged at iter 31, Log-likelihood change = 9.834766e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:49,  2.01it/s]

Iter 000: Log-likelihood = -0.387341

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:26<01:02,  1.12it/s]

Converged at iter 30, Log-likelihood change = -8.642673e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:57,  1.71it/s]

Iter 000: Log-likelihood = -0.387059

 72%|████████████████████████████████████████████████████████████████████████████████████▉                                 | 72/100 [00:43<00:16,  1.67it/s]

Converged at iter 72, Log-likelihood change = 9.834766e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:56,  1.76it/s]

Iter 000: Log-likelihood = -0.387283

 34%|████████████████████████████████████████                                                                              | 34/100 [00:33<01:04,  1.03it/s]

Converged at iter 34, Log-likelihood change = 9.238720e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:49,  2.00it/s]

Iter 000: Log-likelihood = -0.387090

 70%|██████████████████████████████████████████████████████████████████████████████████▌                                   | 70/100 [00:44<00:19,  1.56it/s]

Converged at iter 70, Log-likelihood change = 8.940697e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:30,  3.29it/s]

Iter 000: Log-likelihood = -0.387150

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:12<00:28,  2.45it/s]

Converged at iter 30, Log-likelihood change = 6.854534e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:23,  4.18it/s]

Iter 000: Log-likelihood = -0.387216

 28%|█████████████████████████████████                                                                                     | 28/100 [00:11<00:29,  2.43it/s]

Converged at iter 28, Log-likelihood change = 9.536743e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:13,  1.36it/s]

Iter 000: Log-likelihood = -0.387331

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:31<00:38,  1.42it/s]

Converged at iter 45, Log-likelihood change = -8.344650e-07

Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:37,  2.66it/s]

Iter 000: Log-likelihood = -0.387043

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:22<00:51,  1.36it/s]

Converged at iter 30, Log-likelihood change = -3.874302e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:28,  3.48it/s]

Iter 000: Log-likelihood = -0.386916

 21%|████████████████████████▊                                                                                             | 21/100 [00:13<00:50,  1.57it/s]

Converged at iter 21, Log-likelihood change = 6.556511e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:01<01:52,  1.13s/it]

Iter 000: Log-likelihood = -0.387526

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [03:26<00:00,  2.06s/it]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:45,  2.18it/s]

Iter 000: Log-likelihood = -0.387274

 81%|███████████████████████████████████████████████████████████████████████████████████████████████▌                      | 81/100 [00:42<00:09,  1.91it/s]

Converged at iter 81, Log-likelihood change = 3.874302e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:47,  2.10it/s]

Iter 000: Log-likelihood = -0.386909

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:40<01:23,  1.24s/it]

Converged at iter 33, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:44,  2.25it/s]

Iter 000: Log-likelihood = -0.387120

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:21<00:51,  1.38it/s]

Converged at iter 29, Log-likelihood change = -4.172325e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:17,  1.27it/s]

Iter 000: Log-likelihood = -0.387030

 66%|█████████████████████████████████████████████████████████████████████████████▉                                        | 66/100 [00:51<00:26,  1.27it/s]

Converged at iter 66, Log-likelihood change = -6.258488e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:33,  2.98it/s]

Iter 000: Log-likelihood = -0.387084

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:16<00:44,  1.63it/s]

Converged at iter 27, Log-likelihood change = -2.980232e-08
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:13,  7.31it/s]

Iter 000: Log-likelihood = -0.387135

 28%|█████████████████████████████████                                                                                     | 28/100 [00:03<00:07,  9.05it/s]

Converged at iter 28, Log-likelihood change = 8.940697e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:05,  1.51it/s]

Iter 000: Log-likelihood = -0.387250

 25%|█████████████████████████████▌                                                                                        | 25/100 [00:12<00:37,  2.00it/s]

Converged at iter 25, Log-likelihood change = -2.980232e-07

Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:37,  2.67it/s]

Iter 000: Log-likelihood = -0.386974

 24%|████████████████████████████▎                                                                                         | 24/100 [00:15<00:48,  1.56it/s]

Converged at iter 24, Log-likelihood change = -6.556511e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:08,  1.45it/s]

Iter 000: Log-likelihood = -0.386976

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:04<00:00,  1.56it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:31,  1.08it/s]

Iter 000: Log-likelihood = -0.387484

 38%|████████████████████████████████████████████▊                                                                         | 38/100 [00:37<01:01,  1.01it/s]

Converged at iter 38, Log-likelihood change = -4.470348e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:38,  2.54it/s]

Iter 000: Log-likelihood = -0.387257

 72%|████████████████████████████████████████████████████████████████████████████████████▉                                 | 72/100 [00:33<00:13,  2.14it/s]

Converged at iter 72, Log-likelihood change = 8.344650e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:18,  5.47it/s]

Iter 000: Log-likelihood = -0.386947

 36%|██████████████████████████████████████████▍                                                                           | 36/100 [00:10<00:18,  3.44it/s]

Converged at iter 36, Log-likelihood change = 7.450581e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:36,  2.72it/s]

Iter 000: Log-likelihood = -0.387086

 34%|████████████████████████████████████████                                                                              | 34/100 [00:25<00:50,  1.32it/s]

Converged at iter 34, Log-likelihood change = 8.940697e-08
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:38,  2.55it/s]

Iter 000: Log-likelihood = -0.386977

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:10<00:00,  1.31s/it]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:30,  3.22it/s]

Iter 000: Log-likelihood = -0.387044

 28%|█████████████████████████████████                                                                                     | 28/100 [00:12<00:31,  2.32it/s]

Converged at iter 28, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:16,  5.86it/s]

Iter 000: Log-likelihood = -0.387102

 28%|█████████████████████████████████                                                                                     | 28/100 [00:03<00:09,  7.91it/s]

Converged at iter 28, Log-likelihood change = 9.536743e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:37,  2.65it/s]

Iter 000: Log-likelihood = -0.387010

 28%|█████████████████████████████████                                                                                     | 28/100 [00:20<00:51,  1.40it/s]

Converged at iter 28, Log-likelihood change = 8.344650e-07

Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:37,  2.61it/s]

Iter 000: Log-likelihood = -0.386993

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:16<00:39,  1.80it/s]

Converged at iter 29, Log-likelihood change = 8.344650e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:29,  3.39it/s]

Iter 000: Log-likelihood = -0.386891

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:03<00:08,  8.41it/s]

Converged at iter 30, Log-likelihood change = 6.258488e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:01<01:43,  1.05s/it]

Iter 000: Log-likelihood = -0.397442

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:38<00:00,  1.02it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:47,  2.07it/s]

Iter 000: Log-likelihood = -0.387343

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:39<00:48,  1.13it/s]

Converged at iter 45, Log-likelihood change = 8.344650e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:21,  1.22it/s]

Iter 000: Log-likelihood = -0.386924

 56%|██████████████████████████████████████████████████████████████████                                                    | 56/100 [00:46<00:36,  1.21it/s]

Converged at iter 56, Log-likelihood change = 6.258488e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:48,  2.06it/s]

Iter 000: Log-likelihood = -0.387095

 35%|█████████████████████████████████████████▎                                                                            | 35/100 [00:31<00:59,  1.10it/s]

Converged at iter 35, Log-likelihood change = 6.556511e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:16,  1.29it/s]

Iter 000: Log-likelihood = -0.387115

 50%|███████████████████████████████████████████████████████████                                                           | 50/100 [00:25<00:25,  1.97it/s]

Converged at iter 50, Log-likelihood change = -2.980232e-07
cuda
cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:09, 10.56it/s]

Iter 000: Log-likelihood = -0.387153

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:04<00:11,  6.59it/s]

Converged at iter 27, Log-likelihood change = 5.662441e-07
cuda
cuda

  0%|                                                                                                                               | 0/100 [00:00<?, ?it/s]

Iter 000: Log-likelihood = -0.387128

 65%|████████████████████████████████████████████████████████████████████████████▋                                         | 65/100 [00:15<00:08,  4.12it/s]

Converged at iter 65, Log-likelihood change = 6.854534e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:22,  4.37it/s]

Iter 000: Log-likelihood = -0.387028

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:18<00:45,  1.56it/s]

Converged at iter 29, Log-likelihood change = 5.960464e-07

Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:29,  3.40it/s]

Iter 000: Log-likelihood = -0.387050

 28%|█████████████████████████████████                                                                                     | 28/100 [00:11<00:29,  2.42it/s]

Converged at iter 28, Log-likelihood change = 2.682209e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:34,  2.86it/s]

Iter 000: Log-likelihood = -0.386973

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:21<00:00,  4.67it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:37,  1.01it/s]

Iter 000: Log-likelihood = -0.387569

 77%|██████████████████████████████████████████████████████████████████████████████████████████▊                           | 77/100 [00:43<00:13,  1.76it/s]

Converged at iter 77, Log-likelihood change = 9.238720e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:13,  1.34it/s]

Iter 000: Log-likelihood = -0.387413

 78%|████████████████████████████████████████████████████████████████████████████████████████████                          | 78/100 [01:19<00:22,  1.02s/it]

Converged at iter 78, Log-likelihood change = -1.192093e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.40it/s]

Iter 000: Log-likelihood = -0.387044

 44%|███████████████████████████████████████████████████▉                                                                  | 44/100 [00:39<00:49,  1.13it/s]

Converged at iter 44, Log-likelihood change = -8.344650e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:42,  2.31it/s]

Iter 000: Log-likelihood = -0.387173

 28%|█████████████████████████████████                                                                                     | 28/100 [00:19<00:49,  1.45it/s]

Converged at iter 28, Log-likelihood change = 8.642673e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:53,  1.83it/s]

Iter 000: Log-likelihood = -0.387093

 23%|███████████████████████████▏                                                                                          | 23/100 [00:25<01:24,  1.10s/it]

Converged at iter 23, Log-likelihood change = -3.278255e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:54,  1.82it/s]

Iter 000: Log-likelihood = -0.387169

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:29<00:59,  1.12it/s]

Converged at iter 33, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:29,  3.40it/s]

Iter 000: Log-likelihood = -0.387223

 21%|████████████████████████▊                                                                                             | 21/100 [00:13<00:52,  1.51it/s]

Converged at iter 21, Log-likelihood change = -4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:55,  1.77it/s]

Iter 000: Log-likelihood = -0.387172

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:10<00:23,  2.95it/s]

Converged at iter 31, Log-likelihood change = 8.940697e-07
Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:30,  3.19it/s]

Iter 000: Log-likelihood = -0.387105

 32%|█████████████████████████████████████▊                                                                                | 32/100 [00:18<00:40,  1.70it/s]

Converged at iter 32, Log-likelihood change = 7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:38,  2.60it/s]

Iter 000: Log-likelihood = -0.387040

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:23<01:02,  1.17it/s]

Converged at iter 27, Log-likelihood change = -8.046627e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:33,  1.06it/s]

Iter 000: Log-likelihood = -0.387590

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:44<00:54,  1.01it/s]

Converged at iter 45, Log-likelihood change = 6.556511e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:48,  2.05it/s]

Iter 000: Log-likelihood = -0.387392

 53%|██████████████████████████████████████████████████████████████▌                                                       | 53/100 [00:18<00:16,  2.91it/s]

Converged at iter 53, Log-likelihood change = 7.748604e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:15,  6.33it/s]

Iter 000: Log-likelihood = -0.387013

 37%|███████████████████████████████████████████▋                                                                          | 37/100 [00:14<00:24,  2.54it/s]

Converged at iter 37, Log-likelihood change = 4.470348e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:48,  2.05it/s]

Iter 000: Log-likelihood = -0.387280

 51%|████████████████████████████████████████████████████████████▏                                                         | 51/100 [00:35<00:33,  1.46it/s]

Converged at iter 51, Log-likelihood change = 4.172325e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:49,  2.01it/s]

Iter 000: Log-likelihood = -0.387079

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:36<00:00,  2.74it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:31,  3.18it/s]

Iter 000: Log-likelihood = -0.387164

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:23<00:28,  1.93it/s]

Converged at iter 45, Log-likelihood change = 7.748604e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:27,  3.62it/s]

Iter 000: Log-likelihood = -0.387251

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:26<00:32,  1.71it/s]

Converged at iter 45, Log-likelihood change = 3.278255e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:32,  3.03it/s]

Iter 000: Log-likelihood = -0.387108

 15%|█████████████████▋                                                                                                    | 15/100 [00:05<00:33,  2.56it/s]

Converged at iter 15, Log-likelihood change = -6.258488e-07

Unique performers: 4500
4500
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:59,  1.67it/s]

Iter 000: Log-likelihood = -0.387126

 37%|███████████████████████████████████████████▋                                                                          | 37/100 [00:28<00:48,  1.29it/s]

Converged at iter 37, Log-likelihood change = 7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:32,  3.06it/s]

Iter 000: Log-likelihood = -0.386971

 19%|██████████████████████▍                                                                                               | 19/100 [00:12<00:52,  1.56it/s]

Converged at iter 19, Log-likelihood change = -2.980232e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:30,  1.10it/s]

Iter 000: Log-likelihood = -0.387569

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:26<00:00,  3.79it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:53,  1.84it/s]

Iter 000: Log-likelihood = -0.387374

 45%|█████████████████████████████████████████████████████                                                                 | 45/100 [00:35<00:43,  1.27it/s]

Converged at iter 45, Log-likelihood change = -1.192093e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:44,  2.24it/s]

Iter 000: Log-likelihood = -0.386944

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:25<01:00,  1.16it/s]

Converged at iter 30, Log-likelihood change = 7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:56,  1.75it/s]

Iter 000: Log-likelihood = -0.387172

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:20<00:50,  1.41it/s]

Converged at iter 29, Log-likelihood change = -5.066395e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:19,  1.25it/s]

Iter 000: Log-likelihood = -0.387194

 81%|███████████████████████████████████████████████████████████████████████████████████████████████▌                      | 81/100 [01:01<00:14,  1.33it/s]

Converged at iter 81, Log-likelihood change = 8.046627e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:55,  1.79it/s]

Iter 000: Log-likelihood = -0.387133

 32%|█████████████████████████████████████▊                                                                                | 32/100 [00:19<00:41,  1.65it/s]

Converged at iter 32, Log-likelihood change = 7.748604e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:48,  2.06it/s]

Iter 000: Log-likelihood = -0.387222

 28%|█████████████████████████████████                                                                                     | 28/100 [00:24<01:03,  1.13it/s]

Converged at iter 28, Log-likelihood change = 8.344650e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:55,  1.78it/s]

Iter 000: Log-likelihood = -0.387170

 28%|█████████████████████████████████                                                                                     | 28/100 [00:13<00:33,  2.15it/s]

Converged at iter 28, Log-likelihood change = 9.238720e-07
PGEM | Percent: 10 |Acc: 0.7917 ± 0.0004 | WAcc: 0.8732 ± 0.0003 | Tau: 0.5787 ± 0.0007
Unique performers: 4909
4909
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:33,  2.92it/s]

Iter 000: Log-likelihood = -0.411809

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:21<00:00,  4.56it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:16,  5.84it/s]

Iter 000: Log-likelihood = -0.411732

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:09<00:23,  3.05it/s]

Converged at iter 29, Log-likelihood change = -3.874302e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:35,  1.04it/s]

Iter 000: Log-likelihood = -0.412284

 37%|███████████████████████████████████████████▋                                                                          | 37/100 [00:34<00:58,  1.09it/s]

Converged at iter 37, Log-likelihood change = 5.066395e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:43,  2.28it/s]

Iter 000: Log-likelihood = -0.412069

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:33<01:21,  1.14s/it]

Converged at iter 29, Log-likelihood change = 7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:51,  1.92it/s]

Iter 000: Log-likelihood = -0.411779

 42%|█████████████████████████████████████████████████▌                                                                    | 42/100 [00:35<00:49,  1.17it/s]

Converged at iter 42, Log-likelihood change = 6.556511e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:43,  2.27it/s]

Iter 000: Log-likelihood = -0.411916

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:25<01:01,  1.16it/s]

Converged at iter 29, Log-likelihood change = 4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:51,  1.91it/s]

Iter 000: Log-likelihood = -0.411809

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:21<00:50,  1.38it/s]

Converged at iter 30, Log-likelihood change = -8.344650e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:32,  3.03it/s]

Iter 000: Log-likelihood = -0.411861

 31%|████████████████████████████████████▌                                                                                 | 31/100 [00:19<00:44,  1.56it/s]

Converged at iter 31, Log-likelihood change = 4.172325e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:39,  2.53it/s]

Iter 000: Log-likelihood = -0.411943

 17%|████████████████████                                                                                                  | 17/100 [00:10<00:53,  1.55it/s]

Converged at iter 17, Log-likelihood change = -4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:34,  2.86it/s]

Iter 000: Log-likelihood = -0.411844

 25%|█████████████████████████████▌                                                                                        | 25/100 [00:16<00:48,  1.55it/s]

Converged at iter 25, Log-likelihood change = -2.682209e-07

Unique performers: 4909
4909
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:41,  2.37it/s]

Iter 000: Log-likelihood = -0.411803

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:23<00:46,  1.43it/s]

Converged at iter 33, Log-likelihood change = 5.662441e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:31,  3.11it/s]

Iter 000: Log-likelihood = -0.411692

 20%|███████████████████████▌                                                                                              | 20/100 [00:08<00:33,  2.39it/s]

Converged at iter 20, Log-likelihood change = -3.576279e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:38,  1.01it/s]

Iter 000: Log-likelihood = -0.412189

 33%|██████████████████████████████████████▉                                                                               | 33/100 [00:34<01:10,  1.05s/it]

Converged at iter 33, Log-likelihood change = 5.066395e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.40it/s]

Iter 000: Log-likelihood = -0.412094

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:29<01:08,  1.02it/s]

Converged at iter 30, Log-likelihood change = 7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:12,  1.37it/s]

Iter 000: Log-likelihood = -0.411809

 26%|██████████████████████████████▋                                                                                       | 26/100 [00:17<00:50,  1.46it/s]

Converged at iter 26, Log-likelihood change = 5.960464e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:04,  1.54it/s]

Iter 000: Log-likelihood = -0.411921

 28%|█████████████████████████████████                                                                                     | 28/100 [00:21<00:55,  1.30it/s]

Converged at iter 28, Log-likelihood change = 4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:37,  1.01it/s]

Iter 000: Log-likelihood = -0.411918

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [01:42<00:00,  1.02s/it]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:11,  8.83it/s]

Iter 000: Log-likelihood = -0.411937

 34%|████████████████████████████████████████                                                                              | 34/100 [00:07<00:14,  4.49it/s]

Converged at iter 34, Log-likelihood change = 8.344650e-07
cuda

cuda

  2%|██▍                                                                                                                    | 2/100 [00:00<00:07, 13.30it/s]

Iter 000: Log-likelihood = -0.411906

 26%|██████████████████████████████▋                                                                                       | 26/100 [00:03<00:09,  8.10it/s]

Converged at iter 26, Log-likelihood change = 9.238720e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:15,  6.37it/s]

Iter 000: Log-likelihood = -0.411999

 24%|████████████████████████████▎                                                                                         | 24/100 [00:03<00:10,  7.44it/s]

Converged at iter 24, Log-likelihood change = -6.258488e-07
Unique performers: 4909
4909
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:31,  3.16it/s]

Iter 000: Log-likelihood = -0.411784

 59%|█████████████████████████████████████████████████████████████████████▌                                                | 59/100 [00:25<00:17,  2.34it/s]

Converged at iter 59, Log-likelihood change = -7.450581e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:47,  2.07it/s]

Iter 000: Log-likelihood = -0.411709

 25%|█████████████████████████████▌                                                                                        | 25/100 [00:12<00:36,  2.06it/s]

Converged at iter 25, Log-likelihood change = 8.642673e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:01<01:43,  1.05s/it]

Iter 000: Log-likelihood = -0.412264

 60%|██████████████████████████████████████████████████████████████████████▊                                               | 60/100 [00:33<00:22,  1.80it/s]

Converged at iter 60, Log-likelihood change = 4.768372e-07
cuda

cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:57,  1.73it/s]

Iter 000: Log-likelihood = -0.412109

 12%|██████████████▏                                                                                                       | 12/100 [00:12<01:38,  1.12s/it]

### Addition of Anti-Personas

In [ ]:
spammer_type = "anti"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_anti_personas(df, percent, seed=sd)
        PC_faceage = df_to_pickle_faceage(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Left Position Biased Spammers

In [ ]:
spammer_type = "left"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_position_biased_spammers(df, percent,position_bias="left", seed=sd)
        PC_faceage = df_to_pickle_faceage(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Right Position Biased Spammers

In [ ]:
spammer_type = "right"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_position_biased_spammers(df, percent,position_bias="right", seed=sd)
        PC_faceage = df_to_pickle_faceage(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Equal Proportion of Spammers

In [ ]:
spammer_type = "equal"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_equal_proportion_of_all_spammers(df, percent, seed=sd)
        PC_faceage = df_to_pickle_faceage(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")