***
10 random seeds: range(20, 30)
for data creation for each type of spammer

invoke pgem for 10 random seeds: range(10)

get pgem accuracy (+- std dev), wacc and tau

save in results/spammer_type/pgem.csv
***

## Device Setup

In [1]:
!nvidia-smi

Sun Dec 21 08:11:44 2025
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.5     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:17:00.0 Off |                    0 |
| N/A   50C    P0              66W / 300W |    529MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:31:00.0 Off |                    0 |
| N/A   37C    P0              48W / 300W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          Off | 00000000:4B:00.0 Off |                    0 |
| N/A   74C    P0             333W / 300W |  49971MiB / 81920MiB |     95%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          Off | 00000000:CA:00.0 Off |                    0 |
| N/A   41C    P0              73W / 300W |   2084MiB / 81920MiB |     70%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

In [2]:
import os
import torch
os.environ["CUDA_VISIBLE_DEVICES"] = "3"
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda

In [3]:
print(f"Current PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA version: {torch.version.cuda}")

Current PyTorch version: 2.9.1+cu128
CUDA available: True
CUDA version: 12.8

### Importing PGEM

In [4]:
import sys
sys.path.insert(0, "../")
sys.path.insert(1, "../../")

from spammer_types import *
from util import *
import opt_fair
from distribution_utils import crowd_bt_dist, logistic_preference_dist, comparisons_to_df, safe_kendalltau, to_numpy
from metrics import compute_acc, compute_weighted_acc
from pgem import EMWrapper

## Passage dataset

### Get the original df of passage dataset

In [5]:
df_path = "../../real_data/passage/data/passage_cleaned.csv"

In [6]:
import pandas as pd
df = pd.read_csv(df_path)
def sort_df(df, column_name):
        # Sort by a specific column (replace 'column_name' with your column)
        df_sorted = df.sort_values(by=column_name, ascending=True)  # or ascending=False

        return df_sorted
df = sort_df(df, 'performer')
df[['left', 'right', 'label', 'performer']].head()

,left,right,label,performer
0,been wicked. They believed that the end of the...,lichen Sect Content Linking Artid A snake coil...,lichen Sect Content Linking Artid A snake coil...,5
20,"school, you noticed that all the clocks read a...",man in the seat with me and the two women acro...,man in the seat with me and the two women acro...,5
19,foreign animals or plants may be taken into th...,adhere to the wall. Using sizing that has been...,foreign animals or plants may be taken into th...,5
18,many pennies did each child get Which computat...,the picture on its cover. Write two or three s...,many pennies did each child get Which computat...,5
17,direction of the Sun. The length in meters and...,"the ground going into the cave. Oh, my he said...","the ground going into the cave. Oh, my he said...",5

In [7]:
percents = [10, 20, 40, 60, 80]
# percents = [10]

In [8]:
import pickle

with open("../../real_data/passage/data/PassageDF.pickle", "rb") as handle:
    df_passage = pickle.load(handle)
df_passage

                                                 label  score
0    a star. Our planet, Earth, orbits, or circles,...      1
1    Adam, We did not have plastic toys. I played w...      1
2    Who said the little owl. Who wants to hunt wit...      1
3    dead leaf. This is a mole. Moles burrow underg...      1
4    ereaddatagradepsenvironcomp.html Environment r...      1
..                                                 ...    ...
467  work over the summer on any changes they wish ...     12
468  between January and December plunged the Unite...     12
469  into a newly opened bank account. I was amazed...     12
470  occurring phenomenon, manmade by products are ...     12
471  question requires students to use context clue...     12

[472 rows x 2 columns]

In [9]:
size = len(df_passage)
print(size)
classes = [0] * size
# for faceage it would be classes = df_passage['gender']

472

In [10]:
gt_df = df_passage

### Addition of Random Guessors

In [11]:
spammer_type = "random"

In [12]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [13]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [14]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_random_spammer(df, percent, seed=sd)
        PC_faceage = df_to_pickle(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est).any() or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

Unique performers: 686
686
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:19,  1.25it/s]

Iter 000: Log-likelihood = -0.472055

 82%|████████████████████████████████████████████████████████████████████████████████████████████████▊                     | 82/100 [00:45<00:10,  1.80it/s]

Converged at iter 82, Log-likelihood change = 2.384186e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:57,  1.72it/s]

Iter 000: Log-likelihood = -0.471025

 23%|███████████████████████████▏                                                                                          | 23/100 [00:10<00:36,  2.10it/s]

Converged at iter 23, Log-likelihood change = -4.172325e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:06,  1.49it/s]

Iter 000: Log-likelihood = -0.472944

 10%|███████████▊                                                                                                          | 10/100 [00:05<00:52,  1.72it/s]

Converged at iter 10, Log-likelihood change = 6.556511e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:45,  2.20it/s]

Iter 000: Log-likelihood = -0.472695

 30%|███████████████████████████████████▍                                                                                  | 30/100 [00:16<00:37,  1.87it/s]

Converged at iter 30, Log-likelihood change = 5.960464e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:51,  1.91it/s]

Iter 000: Log-likelihood = -0.473036

 27%|███████████████████████████████▊                                                                                      | 27/100 [00:12<00:32,  2.22it/s]

Converged at iter 27, Log-likelihood change = 2.980232e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:39,  2.49it/s]

Iter 000: Log-likelihood = -0.472684

 16%|██████████████████▉                                                                                                   | 16/100 [00:07<00:41,  2.04it/s]

Converged at iter 16, Log-likelihood change = -8.940697e-08
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.40it/s]

Iter 000: Log-likelihood = -0.472745

 34%|████████████████████████████████████████                                                                              | 34/100 [00:16<00:31,  2.10it/s]

Converged at iter 34, Log-likelihood change = -7.152557e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:03,  1.56it/s]

Iter 000: Log-likelihood = -0.475998

 20%|███████████████████████▌                                                                                              | 20/100 [00:10<00:40,  1.98it/s]

Converged at iter 20, Log-likelihood change = 8.046627e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:42,  2.35it/s]

Iter 000: Log-likelihood = -0.471822

 29%|██████████████████████████████████▏                                                                                   | 29/100 [00:13<00:33,  2.13it/s]

Converged at iter 29, Log-likelihood change = -6.854534e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:00,  1.64it/s]

Iter 000: Log-likelihood = -0.472473

 11%|████████████▉                                                                                                         | 11/100 [00:06<00:49,  1.79it/s]

Converged at iter 11, Log-likelihood change = -7.152557e-07
Unique performers: 686

686
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:02,  1.58it/s]

Iter 000: Log-likelihood = -0.471607

 17%|████████████████████                                                                                                  | 17/100 [00:09<00:48,  1.70it/s]

Converged at iter 17, Log-likelihood change = 8.642673e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:08,  1.45it/s]

Iter 000: Log-likelihood = -0.470652

 65%|████████████████████████████████████████████████████████████████████████████▋                                         | 65/100 [00:33<00:17,  1.97it/s]

Converged at iter 65, Log-likelihood change = -8.046627e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:05,  1.52it/s]

Iter 000: Log-likelihood = -0.472921

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 93/100 [00:45<00:03,  2.05it/s]

Converged at iter 93, Log-likelihood change = 5.066395e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:01,  1.62it/s]

Iter 000: Log-likelihood = -0.472203

 13%|███████████████▎                                                                                                      | 13/100 [00:06<00:41,  2.09it/s]

Converged at iter 13, Log-likelihood change = -3.576279e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:45,  2.17it/s]

Iter 000: Log-likelihood = -0.472593

 28%|█████████████████████████████████                                                                                     | 28/100 [00:15<00:40,  1.77it/s]

Converged at iter 28, Log-likelihood change = -4.470348e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:44,  2.23it/s]

Iter 000: Log-likelihood = -0.472190

 23%|███████████████████████████▏                                                                                          | 23/100 [00:12<00:41,  1.85it/s]

Converged at iter 23, Log-likelihood change = -1.490116e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.41it/s]

Iter 000: Log-likelihood = -0.472367

 12%|██████████████▏                                                                                                       | 12/100 [00:06<00:44,  1.98it/s]

Converged at iter 12, Log-likelihood change = -3.874302e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:01,  1.62it/s]

Iter 000: Log-likelihood = -0.475612

 21%|████████████████████████▊                                                                                             | 21/100 [00:11<00:43,  1.83it/s]

Converged at iter 21, Log-likelihood change = 8.940697e-08
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:00,  1.63it/s]

Iter 000: Log-likelihood = -0.471360

 10%|███████████▊                                                                                                          | 10/100 [00:06<00:56,  1.60it/s]

Converged at iter 10, Log-likelihood change = -7.450581e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:09,  1.42it/s]

Iter 000: Log-likelihood = -0.472096

 10%|███████████▊                                                                                                          | 10/100 [00:05<00:50,  1.77it/s]

Converged at iter 10, Log-likelihood change = -7.152557e-07
Unique performers: 686

686
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:58,  1.70it/s]

Iter 000: Log-likelihood = -0.472194

 54%|███████████████████████████████████████████████████████████████▋                                                      | 54/100 [00:26<00:22,  2.06it/s]

Converged at iter 54, Log-likelihood change = 2.980232e-08
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:10,  1.40it/s]

Iter 000: Log-likelihood = -0.471160

 20%|███████████████████████▌                                                                                              | 20/100 [00:11<00:47,  1.69it/s]

Converged at iter 20, Log-likelihood change = -1.490116e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:50,  1.97it/s]

Iter 000: Log-likelihood = -0.473058

 12%|██████████████▏                                                                                                       | 12/100 [00:07<00:52,  1.66it/s]

Converged at iter 12, Log-likelihood change = -5.662441e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:02,  1.60it/s]

Iter 000: Log-likelihood = -0.474299

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:34<00:00,  2.93it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:14,  1.33it/s]

Iter 000: Log-likelihood = -0.473200

  9%|██████████▋                                                                                                            | 9/100 [00:05<00:56,  1.60it/s]

Converged at iter 9, Log-likelihood change = 1.788139e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:39,  2.53it/s]

Iter 000: Log-likelihood = -0.472783

 15%|█████████████████▋                                                                                                    | 15/100 [00:06<00:35,  2.37it/s]

Converged at iter 15, Log-likelihood change = 7.748604e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:45,  2.17it/s]

Iter 000: Log-likelihood = -0.472896

 23%|███████████████████████████▏                                                                                          | 23/100 [00:11<00:38,  1.98it/s]

Converged at iter 23, Log-likelihood change = 3.576279e-07
cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<01:13,  1.35it/s]

Iter 000: Log-likelihood = -0.534284

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:40<00:00,  2.45it/s]

cuda
cuda

  1%|█▏                                                                                                                     | 1/100 [00:00<00:43,  2.28it/s]

Iter 000: Log-likelihood = -0.471911

 19%|██████████████████████▍                                                                                               | 19/100 [00:07<00:32,  2.49it/s]

### Addition of Anti-Personas

In [ ]:
spammer_type = "anti"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_anti_personas(df, percent, seed=sd)
        PC_faceage = df_to_pickle(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est) or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Left Position Biased Spammers

In [ ]:
spammer_type = "left"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_position_biased_spammers(df, percent,position_bias="left", seed=sd)
        PC_faceage = df_to_pickle(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est) or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Right Position Biased Spammers

In [ ]:
spammer_type = "right"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_position_biased_spammers(df, percent,position_bias="right", seed=sd)
        PC_faceage = df_to_pickle(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est) or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")

### Addition of Equal Proportion of Spammers

In [ ]:
spammer_type = "equal"

In [ ]:
csv_file = f"results/{spammer_type}/pgem.csv"

In [ ]:
import os
os.makedirs(f"results/{spammer_type}", exist_ok=True)

In [ ]:
import csv
# -------------------------
# Write CSV header
# -------------------------
header = [
    "percent",
    "PGEM_acc_mean", "PGEM_acc_std",
    "PGEM_wacc_mean", "PGEM_wacc_std",
    "PGEM_tau_mean", "PGEM_tau_std"
]

with open(csv_file, mode='w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(header)

In [ ]:
max_iter_pgem = 100

for percent in percents:
    # initialize metrics
    PGEM_accs, PGEM_waccs, PGEM_taus = [], [], []
    
    for sd in range(20, 30):
        
        # get df
        random_df, spammer_ids = add_equal_proportion_of_all_spammers(df, percent, seed=sd)
        PC_faceage = df_to_pickle(random_df, df_passage)
        K = len(PC_faceage.keys())
        print(K)
        
        for seed in range(10):
            try:
                pg = EMWrapper(PC_faceage, max_iter_pgem, device, random_seed=seed)
                r_est, beta_est, ll = pg.run_algorithm()
                r_est = to_numpy(r_est)
                if np.isnan(r_est).any() or np.isnan(beta_est) or np.isnan(ll):
                    continue
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
                if PGEM_tau < 0:
                    r_est = -r_est
                PGEM_acc = compute_acc(gt_df, r_est, device)
                PGEM_wacc = compute_weighted_acc(gt_df, r_est, device)
                PGEM_tau = safe_kendalltau(r_est, gt_df['score'].to_numpy())
            
            except Exception as e:
                print(f"PGEM failed due to {e}")
                continue
            PGEM_accs.append(PGEM_acc)
            PGEM_waccs.append(PGEM_wacc)
            PGEM_taus.append(PGEM_tau)
    
    row = [
        percent,
        np.mean(PGEM_accs), np.std(PGEM_accs),
        np.mean(PGEM_waccs), np.std(PGEM_waccs),
        np.mean(PGEM_taus), np.std(PGEM_taus)
    ]
    
    with open(csv_file, mode='a', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(row)
    print(
    f"PGEM | "
    f"Percent: {percent} |"
    f"Acc: {np.mean(PGEM_accs):.4f} ± {np.std(PGEM_accs):.4f} | "
    f"WAcc: {np.mean(PGEM_waccs):.4f} ± {np.std(PGEM_waccs):.4f} | "
    f"Tau: {np.mean(PGEM_taus):.4f} ± {np.std(PGEM_taus):.4f}")